test:
  image: python:3.6
  script:
    - pip3 install -r dev_requirements.txt
    - pycodestyle src spec
    - cp config/config-ci.json config/config.json
    - coverage run -m unittest spec/*/*/*.py
    - coverage report

deploy-experiments:
  stage: deploy
  image: nikolaik/python-nodejs
  environment:
    name: experiments
    url: https://starter-python.experiments.neosperiencecloud.com/v1/thing
  variables:
    AWS_ACCESS_KEY_ID: $EXPERIMENTS_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $EXPERIMENTS_AWS_SECRET_ACCESS_KEY
    SERVERLESS_STAGE: dev
    SERVERLESS_REGION: eu-west-1
    SERVERLESS_CUSTOM_DOMAIN_NAME_BASE_DOMAIN_NAME: starter-python.experiments.neosperiencecloud.com
    CONFIG_LOGGING_LEVEL: DEBUG
  before_script:
    - npm install
  script:
    - apt-get update -y && apt-get install gettext-base -y
    - envsubst < "config/config.json.dist" > "config/config.json"
    - npm run sls -- deploy
    - rm config/config.json
  only:
    - master
