test:
  image: python:3.6
  script:
    - pip3 install -r dev_requirements.txt
    - pycodestyle src
    - coverage run -m unittest src/spec/*/*/*.py -v
    - coverage report

deploy-experiments:
  stage: deploy
  image: nikolaik/python-nodejs
  environment:
    name: experiments
    url: https://starter-python.experiments.neosperiencecloud.com/v1/thing
  variables:
    AWS_ACCESS_KEY_ID: $EXPERIMENTS_AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $EXPERIMENTS_AWS_SECRET_ACCESS_KEY
    SERVERLESS_ACCOUNT_ID: $EXPERIMENTS_AWS_ACCOUNT_ID
    SERVERLESS_STAGE: dev
    SERVERLESS_REGION: eu-west-1
    SERVERLESS_CUSTOM_DOMAIN_NAME_BASE_DOMAIN_NAME: starter-python.experiments.neosperiencecloud.com
    CONFIG_LOGGER_CONSOLE_OPTIONS_LEVEL: verbose
    CONFIG_LOGGER_FILE_OPTIONS_LEVEL: verbose
    CONFIG_LOGGER_FILE_OPTIONS_FILENAME: logs/dev.log
  before_script:
    - npm install
  script:
    - apt-get update -y && apt-get install gettext-base -y
    - envsubst < "config/config.json.dist" > "config/config.json"
    - npm run sls -- package
    - node scripts/adjust-serverless-state.js
    - npm run sls -- deploy --package .serverless
    - rm config/config.json
  only:
    - master
